# dummy conf for reference to create the parser 

# cpu_idle_threshold: "15"
# watch_path: "/home/user/Downloads"

# folders:
#   Images:
#     path: "/home/user/Pictures"
#     extensions: [".jpg", ".jpeg", ".png", ".gif"]
#   Documents:
#     path: "/home/user/Documents"
#     extensions: [".pdf", ".txt", ".docx"]